[URL]
passage=https://www.biblegateway.com/passage/?search={}&version={}&interface=print
votd=https://www.biblegateway.com/votd/get/?format=json&version=NKJV

[DEFAULT]
search_type=ALL
empty_message:empty