# Example configuration for mmrelay integration
# This shows how to enable the detect_references_anywhere feature

version: 1
matrix:
  room_ids:
    - "!your_room_id:your_homeserver_domain"

# Bot behavior configuration - uncommented to enable mmrelay support
bot:
  # Default Bible translation to use when none is specified
  default_translation: kjv # Options: "kjv", "esv" (ESV requires api_keys.esv)

  # Enable or disable caching of Bible passages
  cache_enabled: true

  # Preserve poetry formatting (newlines kept; HTML uses <br />)
  preserve_poetry_formatting: false

  # Maximum length for bot messages (characters)
  # Messages longer than this will be truncated with "..."
  max_message_length: 2000

  # Split long messages into multiple messages of specified length
  # Set to 0 or null to disable message splitting (default behavior)
  split_message_length: 0 # Disabled by default

  # Detect scripture references anywhere in messages (ENABLED for mmrelay)
  # When false: only responds to messages that are ONLY scripture references ("John 3:16")
  # When true: detects references anywhere in messages ("Have you read John 3:16 ESV?")
  # Useful for integration with relay bots like meshtastic-matrix-relay
  detect_references_anywhere: true # <-- SET TO TRUE FOR MMRELAY SUPPORT

# API Keys for Bible translations (optional)
# api_keys:
#   esv: null
